const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const router = require('./router')
app.use('/',(req,res,next)=>{
    res.header('Access-Control-Allow-Origin','*')
    res.header('Access-Control-Allow-Headers','Origin, X-Requested-With, Content-Type, Accept')
    next()
})
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:true}))
app.use('/api',router)
app.listen(9000,()=>{
    console.log("started the server on port 9000")
})
